"""
Shoot the Sheet - Country Registry

Canonical country metadata derived from countries.json.
"""

from typing import Dict, List, Optional, TypedDict


class CountryDef(TypedDict):
    name: str
    aliases: List[str]
    sovereign: Optional[str]


COUNTRIES: Dict[str, CountryDef] = {
    "AFG": {
        "name": "Afghanistan",
        "aliases": [
            "AFG",
            "Afghanistan",
            "Islamic Republic of Afghanistan",
            "Afganistan",
        ],
        "sovereign": None,
    },
    "ALB": {
        "name": "Albania",
        "aliases": ["ALB", "Albania", "Republic of Albania"],
        "sovereign": None,
    },
    "ALG": {
        "name": "Algeria",
        "aliases": [
            "ALG",
            "DZA",
            "Algeria",
            "People's Democratic Republic of Algeria",
            "Democratic Republic of Algeria",
        ],
        "sovereign": None,
    },
    "AND": {
        "name": "Andorra",
        "aliases": ["AND", "Andorra", "Principality of Andorra"],
        "sovereign": None,
    },
    "ANG": {
        "name": "Angola",
        "aliases": ["ANG", "AGO", "Angola", "Republic of Angola"],
        "sovereign": None,
    },
    "ANT": {
        "name": "Antigua & Barbuda",
        "aliases": ["ANT", "ATG", "Antigua & Barbuda", "Antigua", "Barbuda"],
        "sovereign": None,
    },
    "ARG": {
        "name": "Argentina",
        "aliases": ["ARG", "Argentina", "Argentine Republic"],
        "sovereign": None,
    },
    "ARM": {
        "name": "Armenia",
        "aliases": ["ARM", "Armenia", "Republic of Armenia"],
        "sovereign": None,
    },
    "ARU": {
        "name": "Aruba",
        "aliases": ["ARU", "ABW", "Aruba"],
        "sovereign": "NED",
    },
    "ASA": {
        "name": "American Samoa",
        "aliases": ["ASA", "ASM", "American Samoa"],
        "sovereign": "USA",
    },
    "AUS": {
        "name": "Australia",
        "aliases": [
            "AUS",
            "Australia",
            "Commonwealth of Australia",
            "NIS",
            "NFK",
            "Norfolk Island",
            "Territory of Norfolk Island",
            "CXR",
            "Christmas Island",
            "Territory of Christmas Island",
            "CCK",
            "Cocos Islands",
            "Territory of the Cocos Islands",
        ],
        "sovereign": None,
    },
    "AUT": {
        "name": "Austria",
        "aliases": ["AUT", "Austria", "Republic of Austria"],
        "sovereign": None,
    },
    "AZE": {
        "name": "Azerbaijan",
        "aliases": ["AZE", "Azerbaijan", "Republic of Azerbaijan", "AZ"],
        "sovereign": None,
    },
    "BAH": {
        "name": "Bahamas",
        "aliases": [
            "BAH",
            "BHS",
            "Bahamas",
            "Commonwealth of the Bahamas",
            "The Bahamas",
        ],
        "sovereign": None,
    },
    "BAN": {
        "name": "Bangladesh",
        "aliases": ["BAN", "BGD", "Bangladesh", "People's Republic of Bangladesh"],
        "sovereign": None,
    },
    "BAR": {
        "name": "Barbados",
        "aliases": ["BAR", "BRB", "Barbados"],
        "sovereign": None,
    },
    "BDI": {
        "name": "Burundi",
        "aliases": ["BDI", "Burundi", "Republic of Burundi"],
        "sovereign": None,
    },
    "BEL": {
        "name": "Belgium",
        "aliases": ["BEL", "Belgium", "Kingdom of Belgium", "BE"],
        "sovereign": None,
    },
    "BEN": {
        "name": "Benin",
        "aliases": ["BEN", "Benin", "Republic of Benin"],
        "sovereign": None,
    },
    "BER": {
        "name": "Bermuda",
        "aliases": [
            "BER",
            "BMU",
            "Bermuda",
            "The Islands of Bermuda",
            "The Bermudas",
            "Bermudas",
        ],
        "sovereign": "GBR",
    },
    "BHU": {
        "name": "Bhutan",
        "aliases": ["BHU", "BTN", "Bhutan", "Kingdom of Bhutan"],
        "sovereign": None,
    },
    "BIH": {
        "name": "Bosnia & Herzegovina",
        "aliases": [
            "BIH",
            "Bosnia & Herzegovina",
            "Bosnia-Herzegovina",
            "Bosnia Herzegovina",
            "Bosnia",
            "Herzegovina",
        ],
        "sovereign": None,
    },
    "BIZ": {
        "name": "Belize",
        "aliases": ["BIZ", "BLZ", "Belize"],
        "sovereign": None,
    },
    "BLR": {
        "name": "Belarus",
        "aliases": ["BLR", "Belarus", "Republic of Belarus"],
        "sovereign": None,
    },
    "BOL": {
        "name": "Bolivia",
        "aliases": ["BOL", "Bolivia", "Plurinational State of Bolivia"],
        "sovereign": None,
    },
    "BOT": {
        "name": "Botswana",
        "aliases": ["BOT", "BWA", "Botswana", "Republic of Botswana"],
        "sovereign": None,
    },
    "BRA": {
        "name": "Brazil",
        "aliases": ["BRA", "Brazil", "Federative Republic of Brazil", "BR"],
        "sovereign": None,
    },
    "BRN": {
        "name": "Bahrain",
        "aliases": ["BRN", "BHR", "Bahrain", "Kingdom of Bahrain"],
        "sovereign": None,
    },
    "BRU": {
        "name": "Brunei",
        "aliases": [
            "BRU",
            "Brunei",
            "Nation of Brunei Abode of Peace",
            "Brunei Darussalam",
            "Nation of Brunei",
        ],
        "sovereign": None,
    },
    "BUL": {
        "name": "Bulgaria",
        "aliases": ["BUL", "BGR", "Bulgaria", "Republic of Bulgaria"],
        "sovereign": None,
    },
    "BUR": {
        "name": "Burkina Faso",
        "aliases": ["BUR", "BFA", "Burkina Faso", "BF", "Burkina"],
        "sovereign": None,
    },
    "CAF": {
        "name": "Central African Republic",
        "aliases": ["CAF", "CAR", "Central African Republic"],
        "sovereign": None,
    },
    "CAL": {
        "name": "New Caledonia",
        "aliases": ["CAL", "NCL", "New Caledonia", "Caledonia"],
        "sovereign": "FRA",
    },
    "CAM": {
        "name": "Cambodia",
        "aliases": ["CAM", "KHM", "Cambodia", "Kingdom of Cambodia"],
        "sovereign": None,
    },
    "CAN": {
        "name": "Canada",
        "aliases": ["CAN", "Canada", "CA"],
        "sovereign": None,
    },
    "CAY": {
        "name": "Cayman Islands",
        "aliases": ["CAY", "CYM", "Cayman Islands", "Cayman"],
        "sovereign": "GBR",
    },
    "CGO": {
        "name": "Republic of the Congo",
        "aliases": ["CGO", "COG", "Congo", "Republic of the Congo"],
        "sovereign": None,
    },
    "CHA": {
        "name": "Chad",
        "aliases": ["CHA", "TCD", "Chad", "Republic of Chad"],
        "sovereign": None,
    },
    "CHI": {
        "name": "Chile",
        "aliases": ["CHI", "CHL", "Chile", "Republic of Chile"],
        "sovereign": None,
    },
    "CHN": {
        "name": "China",
        "aliases": ["CHN", "China", "People's Republic of China"],
        "sovereign": None,
    },
    "CIV": {
        "name": "Ivory Coast",
        "aliases": [
            "CIV",
            "Ivory Coast",
            "Republic of Cote d'Ivoire",
            "Cote d'Ivoire",
            "Republic of Ivory Coast",
        ],
        "sovereign": None,
    },
    "CMR": {
        "name": "Cameroon",
        "aliases": ["CMR", "Cameroon", "Republic of Cameroon"],
        "sovereign": None,
    },
    "COD": {
        "name": "Democratic Republic of the Congo",
        "aliases": [
            "COD",
            "DR Congo",
            "Democratic Republic of the Congo",
            "Congo the Democratic Republic of the",
            "Democratic Republic of Congo",
            "DRC",
        ],
        "sovereign": None,
    },
    "COK": {
        "name": "Cook Islands",
        "aliases": ["COK", "Cook Islands"],
        "sovereign": "NZL",
    },
    "COL": {
        "name": "Colombia",
        "aliases": ["COL", "Colombia", "Republic of Colombia"],
        "sovereign": None,
    },
    "COM": {
        "name": "Comoros",
        "aliases": ["COM", "Comoros", "Union of the Comoros"],
        "sovereign": None,
    },
    "CPV": {
        "name": "Cape Verde",
        "aliases": ["CPV", "Cape Verde", "Republic of Cabo Verde", "CV"],
        "sovereign": None,
    },
    "CRC": {
        "name": "Costa Rica",
        "aliases": ["CRC", "CRI", "Costa Rica", "Republic of Costa Rica", "CR"],
        "sovereign": None,
    },
    "CRO": {
        "name": "Croatia",
        "aliases": ["CRO", "HRV", "Croatia", "Republic of Croatia"],
        "sovereign": None,
    },
    "CUB": {
        "name": "Cuba",
        "aliases": ["CUB", "Cuba", "Republic of Cuba"],
        "sovereign": None,
    },
    "CYP": {
        "name": "Cyprus",
        "aliases": ["CYP", "Cyprus", "Republic of Cyprus"],
        "sovereign": None,
    },
    "CZE": {
        "name": "Czech Republic",
        "aliases": ["CZE", "Czechia", "Czech Republic", "Czech"],
        "sovereign": None,
    },
    "DEN": {
        "name": "Denmark",
        "aliases": [
            "DEN",
            "DNK",
            "Denmark",
            "Kingdom of Denmark",
            "GRL",
            "Greenland",
            "FRO",
            "Faroe Islands",
        ],
        "sovereign": None,
    },
    "DJI": {
        "name": "Djibouti",
        "aliases": ["DJI", "Djibouti", "Republic of Djibouti"],
        "sovereign": None,
    },
    "DMA": {
        "name": "Dominica",
        "aliases": ["DMA", "Dominica", "Commonwealth of Dominica"],
        "sovereign": None,
    },
    "DOM": {
        "name": "Dominican Republic",
        "aliases": ["DOM", "Dominican Republic"],
        "sovereign": None,
    },
    "ECU": {
        "name": "Ecuador",
        "aliases": ["ECU", "Ecuador", "Republic of Ecuador"],
        "sovereign": None,
    },
    "EGY": {
        "name": "Egypt",
        "aliases": ["EGY", "Egypt", "Arab Republic of Egypt", "Republic of Egypt"],
        "sovereign": None,
    },
    "ERI": {
        "name": "Eritrea",
        "aliases": ["ERI", "Eritrea", "State of Eritrea"],
        "sovereign": None,
    },
    "ESA": {
        "name": "El Salvador",
        "aliases": ["ESA", "SLV", "El Salvador", "Republic of El Salvador"],
        "sovereign": None,
    },
    "ESP": {
        "name": "Spain",
        "aliases": ["ESP", "Spain", "Kingdom of Spain"],
        "sovereign": None,
    },
    "EST": {
        "name": "Estonia",
        "aliases": ["EST", "Estonia", "Republic of Estonia"],
        "sovereign": None,
    },
    "ETH": {
        "name": "Ethiopia",
        "aliases": ["ETH", "Ethiopia", "Federal Democratic Republic of Ethiopia"],
        "sovereign": None,
    },
    "FIJ": {
        "name": "Fiji",
        "aliases": ["FIJ", "FJI", "Fiji", "Republic of Fiji"],
        "sovereign": None,
    },
    "FIN": {
        "name": "Finland",
        "aliases": [
            "FIN",
            "Finland",
            "Republic of Finland",
            "ALA",
            "Aland Islands",
            "Aaland",
            "Aland",
        ],
        "sovereign": None,
    },
    "FRA": {
        "name": "France",
        "aliases": [
            "FRA",
            "France",
            "French Republic",
            "FR",
            "GUF",
            "French Guiana",
            "Guiana",
            "GLP",
            "Guadeloupe",
            "MTQ",
            "Martinique",
            "MYT",
            "Mayotte",
            "Department of Mayotte",
            "REU",
            "Reunion",
            "Reunion Island",
            "BLM",
            "St. Barthelemy",
            "Collectivity of St. Barthelemy",
            "MAF",
            "St. Martin",
            "Collectivity of St. Martin",
            "SPM",
            "St. Pierre & Miquelon",
            "Collectivite territoriale de St.-Pierre-et-Miquelon",
            "WLF",
            "Wallis & Futuna",
            "Territory of the Wallis & Futuna Islands",
            "WF",
        ],
        "sovereign": None,
    },
    "FSM": {
        "name": "Micronesia",
        "aliases": [
            "FSM",
            "Micronesia",
            "Federated States of Micronesia",
            "Micronesia Federated States of",
        ],
        "sovereign": None,
    },
    "GAB": {
        "name": "Gabon",
        "aliases": ["GAB", "Gabon", "Gabonese Republic"],
        "sovereign": None,
    },
    "GAM": {
        "name": "Gambia",
        "aliases": ["GAM", "GMB", "Gambia", "Republic of the Gambia", "The Gambia"],
        "sovereign": None,
    },
    "GBR": {
        "name": "Great Britain",
        "aliases": [
            "GBR",
            "United Kingdom",
            "United Kingdom of Great Britain & Northern Ireland",
            "GB",
            "UK",
            "Great Britain",
            "JEY",
            "Jersey",
            "Bailiwick of Jersey",
            "GGY",
            "Guernsey",
            "Bailiwick of Guernsey",
            "IMN",
            "Isle of Man",
            "ENG",
            "England",
            "SCO",
            "SCT",
            "Scotland",
            "WLS",
            "Wales",
            "PCN",
            "Pitcairn Islands",
            "Pitcairn Group of Islands",
            "SHN",
            "St. Helena",
            "FLK",
            "Falkland Islands",
            "FK",
            "AIA",
            "Anguilla",
            "Britain",
        ],
        "sovereign": None,
    },
    "GBS": {
        "name": "Guinea-Bissau",
        "aliases": [
            "GBS",
            "GNB",
            "Guinea-Bissau",
            "Republic of Guinea-Bissau",
            "Guinea Bissau",
        ],
        "sovereign": None,
    },
    "GEO": {
        "name": "Georgia",
        "aliases": ["GEO", "Georgia"],
        "sovereign": None,
    },
    "GEQ": {
        "name": "Equatorial Guinea",
        "aliases": ["GEQ", "GNQ", "Equatorial Guinea", "Republic of Equatorial Guinea"],
        "sovereign": None,
    },
    "GER": {
        "name": "Germany",
        "aliases": ["GER", "DEU", "Germany", "Federal Republic of Germany"],
        "sovereign": None,
    },
    "GHA": {
        "name": "Ghana",
        "aliases": ["GHA", "Ghana", "Republic of Ghana"],
        "sovereign": None,
    },
    "GIB": {
        "name": "Gibraltar",
        "aliases": ["GIB", "Gibraltar"],
        "sovereign": "GBR",
    },
    "GRE": {
        "name": "Greece",
        "aliases": ["GRE", "GRC", "Greece", "Hellenic Republic"],
        "sovereign": None,
    },
    "GRN": {
        "name": "Grenada",
        "aliases": ["GRN", "GRD", "Grenada"],
        "sovereign": None,
    },
    "GUA": {
        "name": "Guatemala",
        "aliases": ["GUA", "GTM", "Guatemala", "Republic of Guatemala"],
        "sovereign": None,
    },
    "GUI": {
        "name": "Guinea",
        "aliases": ["GUI", "GIN", "Guinea", "Republic of Guinea"],
        "sovereign": None,
    },
    "GUM": {
        "name": "Guam",
        "aliases": ["GUM", "Guam"],
        "sovereign": "USA",
    },
    "GUY": {
        "name": "Guyana",
        "aliases": [
            "GUY",
            "Guyana",
            "Co-operative Republic of Guyana",
            "Republic of Guyana",
        ],
        "sovereign": None,
    },
    "HAI": {
        "name": "Haiti",
        "aliases": ["HAI", "HTI", "Haiti", "Republic of Haiti"],
        "sovereign": None,
    },
    "HKG": {
        "name": "Hong Kong",
        "aliases": [
            "HKG",
            "Hong Kong",
            "Hong Kong Special Administrative Region of the People's Republic of China",
            "HK",
            "Hong Kong China",
        ],
        "sovereign": "CHN",
    },
    "HON": {
        "name": "Honduras",
        "aliases": ["HON", "HND", "Honduras", "Republic of Honduras"],
        "sovereign": None,
    },
    "HUN": {
        "name": "Hungary",
        "aliases": ["HUN", "Hungary"],
        "sovereign": None,
    },
    "INA": {
        "name": "Indonesia",
        "aliases": ["INA", "IDN", "Indonesia", "Republic of Indonesia"],
        "sovereign": None,
    },
    "IND": {
        "name": "India",
        "aliases": ["IND", "India", "Republic of India"],
        "sovereign": None,
    },
    "IRI": {
        "name": "Iran",
        "aliases": [
            "IRI",
            "IRN",
            "Iran",
            "Islamic Republic of Iran",
            "Republic of Iran",
        ],
        "sovereign": None,
    },
    "IRL": {
        "name": "Ireland",
        "aliases": ["IRL", "Ireland", "Republic of Ireland", "NIR", "Northern Ireland"],
        "sovereign": None,
    },
    "IRQ": {
        "name": "Iraq",
        "aliases": ["IRQ", "Iraq", "Republic of Iraq", "IQ"],
        "sovereign": None,
    },
    "ISL": {
        "name": "Iceland",
        "aliases": ["ISL", "Iceland", "Republic of Iceland"],
        "sovereign": None,
    },
    "ISR": {
        "name": "Israel",
        "aliases": ["ISR", "Israel", "State of Israel"],
        "sovereign": None,
    },
    "ISV": {
        "name": "United States Virgin Islands",
        "aliases": [
            "ISV",
            "VIR",
            "United States Virgin Islands",
            "Virgin Islands of the United States",
            "Virgin Islands US",
            "US Virgin Islands",
            "Virgin Islands",
        ],
        "sovereign": "USA",
    },
    "ITA": {
        "name": "Italy",
        "aliases": ["ITA", "Italy", "Italian Republic"],
        "sovereign": None,
    },
    "IVB": {
        "name": "British Virgin Islands",
        "aliases": ["IVB", "VGB", "British Virgin Islands", "Virgin Islands British"],
        "sovereign": "GBR",
    },
    "JAM": {
        "name": "Jamaica",
        "aliases": ["JAM", "Jamaica", "JM"],
        "sovereign": None,
    },
    "JOR": {
        "name": "Jordan",
        "aliases": [
            "JOR",
            "Jordan",
            "Hashemite Kingdom of Jordan",
            "Kingdom of Jordan",
        ],
        "sovereign": None,
    },
    "JPN": {
        "name": "Japan",
        "aliases": ["JPN", "Japan"],
        "sovereign": None,
    },
    "KAZ": {
        "name": "Kazakhstan",
        "aliases": ["KAZ", "Kazakhstan", "Republic of Kazakhstan"],
        "sovereign": None,
    },
    "KEN": {
        "name": "Kenya",
        "aliases": ["KEN", "Kenya", "Republic of Kenya", "KE"],
        "sovereign": None,
    },
    "KGZ": {
        "name": "Kyrgyzstan",
        "aliases": ["KGZ", "Kyrgyzstan", "Kyrgyz Republic", "KG"],
        "sovereign": None,
    },
    "KIR": {
        "name": "Kiribati",
        "aliases": [
            "KIR",
            "Kiribati",
            "Independent & Sovereign Republic of Kiribati",
            "KI",
            "Republic of Kiribati",
        ],
        "sovereign": None,
    },
    "KOR": {
        "name": "South Korea",
        "aliases": [
            "KOR",
            "South Korea",
            "Republic of Korea",
            "Korea Republic of",
            "Korea",
        ],
        "sovereign": None,
    },
    "KOS": {
        "name": "Kosovo",
        "aliases": ["KOS", "UNK", "Kosovo", "Republic of Kosovo"],
        "sovereign": None,
    },
    "KSA": {
        "name": "Saudi Arabia",
        "aliases": [
            "KSA",
            "SAU",
            "Saudi Arabia",
            "Kingdom of Saudi Arabia",
            "Saudi",
            "Arabia",
            "SA",
        ],
        "sovereign": None,
    },
    "KUW": {
        "name": "Kuwait",
        "aliases": ["KUW", "KWT", "Kuwait", "State of Kuwait", "KW"],
        "sovereign": None,
    },
    "LAO": {
        "name": "Laos",
        "aliases": ["LAO", "Laos", "Lao People's Democratic Republic"],
        "sovereign": None,
    },
    "LAT": {
        "name": "Latvia",
        "aliases": ["LAT", "LVA", "Latvia", "Republic of Latvia"],
        "sovereign": None,
    },
    "LBA": {
        "name": "Libya",
        "aliases": ["LBA", "LBY", "Libya", "State of Libya"],
        "sovereign": None,
    },
    "LBN": {
        "name": "Lebanon",
        "aliases": ["LBN", "Lebanon", "Lebanese Republic"],
        "sovereign": None,
    },
    "LBR": {
        "name": "Liberia",
        "aliases": ["LBR", "Liberia", "Republic of Liberia"],
        "sovereign": None,
    },
    "LCA": {
        "name": "St Lucia",
        "aliases": ["LCA", "St. Lucia", "Lucia"],
        "sovereign": None,
    },
    "LES": {
        "name": "Lesotho",
        "aliases": ["LES", "LSO", "Lesotho", "Kingdom of Lesotho"],
        "sovereign": None,
    },
    "LIE": {
        "name": "Liechtenstein",
        "aliases": ["LIE", "Liechtenstein", "Principality of Liechtenstein"],
        "sovereign": None,
    },
    "LTU": {
        "name": "Lithuania",
        "aliases": ["LTU", "Lithuania", "Republic of Lithuania"],
        "sovereign": None,
    },
    "LUX": {
        "name": "Luxembourg",
        "aliases": ["LUX", "Luxembourg", "Grand Duchy of Luxembourg"],
        "sovereign": None,
    },
    "MAC": {
        "name": "Macau",
        "aliases": [
            "MAC",
            "Macau",
            "Macao",
            "Macao China",
            "Macau China",
            "Macao Special Administrative Region of the People's Republic of China",
        ],
        "sovereign": "CHN",
    },
    "MAD": {
        "name": "Madagascar",
        "aliases": ["MAD", "MDG", "Madagascar", "Republic of Madagascar"],
        "sovereign": None,
    },
    "MAR": {
        "name": "Morocco",
        "aliases": [
            "MAR",
            "Morocco",
            "Kingdom of Morocco",
            "ESH",
            "Western Sahara",
            "Sahrawi Arab Democratic Republic",
        ],
        "sovereign": None,
    },
    "MAS": {
        "name": "Malaysia",
        "aliases": ["MAS", "MYS", "Malaysia"],
        "sovereign": None,
    },
    "MAT": {
        "name": "Montserrat",
        "aliases": ["MAT", "MSR", "Montserrat"],
        "sovereign": "GBR",
    },
    "MAW": {
        "name": "Malawi",
        "aliases": ["MAW", "MWI", "Malawi", "Republic of Malawi"],
        "sovereign": None,
    },
    "MDA": {
        "name": "Moldova",
        "aliases": ["MDA", "Moldova", "Republic of Moldova", "Moldova Republic of"],
        "sovereign": None,
    },
    "MDV": {
        "name": "Maldives",
        "aliases": ["MDV", "Maldives", "Republic of the Maldives"],
        "sovereign": None,
    },
    "MEX": {
        "name": "Mexico",
        "aliases": ["MEX", "Mexico", "United Mexican States", "MX"],
        "sovereign": None,
    },
    "MGL": {
        "name": "Mongolia",
        "aliases": ["MGL", "MNG", "Mongolia"],
        "sovereign": None,
    },
    "MHL": {
        "name": "Marshall Islands",
        "aliases": ["MHL", "Marshall Islands", "Republic of the Marshall Islands"],
        "sovereign": None,
    },
    "MKD": {
        "name": "North Macedonia",
        "aliases": [
            "MKD",
            "North Macedonia",
            "Republic of North Macedonia",
            "The former Yugoslav Republic of Macedonia",
            "Macedonia",
            "Republic of Macedonia",
        ],
        "sovereign": None,
    },
    "MLI": {
        "name": "Mali",
        "aliases": ["MLI", "Mali", "Republic of Mali"],
        "sovereign": None,
    },
    "MLT": {
        "name": "Malta",
        "aliases": ["MLT", "Malta", "Republic of Malta"],
        "sovereign": None,
    },
    "MNE": {
        "name": "Montenegro",
        "aliases": ["MNE", "Montenegro"],
        "sovereign": None,
    },
    "MON": {
        "name": "Monaco",
        "aliases": ["MON", "MCO", "Monaco", "Principality of Monaco"],
        "sovereign": None,
    },
    "MOZ": {
        "name": "Mozambique",
        "aliases": ["MOZ", "Mozambique", "Republic of Mozambique"],
        "sovereign": None,
    },
    "MRI": {
        "name": "Mauritius",
        "aliases": ["MRI", "MUS", "Mauritius", "Republic of Mauritius"],
        "sovereign": None,
    },
    "MTN": {
        "name": "Mauritania",
        "aliases": ["MTN", "MRT", "Mauritania", "Islamic Republic of Mauritania"],
        "sovereign": None,
    },
    "MYA": {
        "name": "Myanmar",
        "aliases": [
            "MYA",
            "MMR",
            "Myanmar",
            "Republic of the Union of Myanmar",
            "Burma",
        ],
        "sovereign": None,
    },
    "NAM": {
        "name": "Namibia",
        "aliases": ["NAM", "Namibia", "Republic of Namibia"],
        "sovereign": None,
    },
    "NCA": {
        "name": "Nicaragua",
        "aliases": ["NCA", "NIC", "Nicaragua", "Republic of Nicaragua"],
        "sovereign": None,
    },
    "NED": {
        "name": "Netherlands",
        "aliases": [
            "NED",
            "NLD",
            "Netherlands",
            "Kingdom of the Netherlands",
            "Holland",
            "The Netherlands",
            "Caribbean Netherlands",
            "BES",
            "BES islands",
            "Bonaire",
            "Sint Eustatius",
            "Saba",
            "Bonaire Sint Eustatius and Saba",
            "Eustatius",
            "CUW",
            "Curacao",
            "Country of Curacao",
            "SXM",
            "Sint Maarten",
            "Maarten",
        ],
        "sovereign": None,
    },
    "NEP": {
        "name": "Nepal",
        "aliases": ["NEP", "NPL", "Nepal", "Federal Democratic Republic of Nepal"],
        "sovereign": None,
    },
    "NGR": {
        "name": "Nigeria",
        "aliases": ["NGR", "NGA", "Nigeria", "Federal Republic of Nigeria"],
        "sovereign": None,
    },
    "NIG": {
        "name": "Niger",
        "aliases": ["NIG", "NER", "Niger", "Republic of Niger"],
        "sovereign": None,
    },
    "NMI": {
        "name": "Northern Mariana Islands",
        "aliases": [
            "NMI",
            "MNP",
            "Northern Mariana Islands",
            "Commonwealth of the Northern Mariana Islands",
        ],
        "sovereign": "USA",
    },
    "NOR": {
        "name": "Norway",
        "aliases": ["NOR", "Norway", "Kingdom of Norway", "NO"],
        "sovereign": None,
    },
    "NRU": {
        "name": "Nauru",
        "aliases": ["NRU", "Nauru", "Republic of Nauru"],
        "sovereign": None,
    },
    "NZL": {
        "name": "New Zealand",
        "aliases": ["NZL", "New Zealand", "NZ", "TKL", "Tokelau", "NIU", "Niue"],
        "sovereign": None,
    },
    "OMA": {
        "name": "Oman",
        "aliases": ["OMA", "OMN", "Oman", "Sultanate of Oman"],
        "sovereign": None,
    },
    "PAK": {
        "name": "Pakistan",
        "aliases": [
            "PAK",
            "Pakistan",
            "Islamic Republic of Pakistan",
            "Republic of Pakistan",
        ],
        "sovereign": None,
    },
    "PAN": {
        "name": "Panama",
        "aliases": ["PAN", "Panama", "Republic of Panama"],
        "sovereign": None,
    },
    "PAR": {
        "name": "Paraguay",
        "aliases": ["PAR", "PRY", "Paraguay", "Republic of Paraguay"],
        "sovereign": None,
    },
    "PER": {
        "name": "Peru",
        "aliases": ["PER", "Peru", "Republic of Peru"],
        "sovereign": None,
    },
    "PHI": {
        "name": "Philippines",
        "aliases": ["PHI", "PHL", "Philippines", "Republic of the Philippines"],
        "sovereign": None,
    },
    "PLE": {
        "name": "Palestine",
        "aliases": [
            "PLE",
            "PSE",
            "Palestine",
            "State of Palestine",
            "Palestine State of",
        ],
        "sovereign": None,
    },
    "PLW": {
        "name": "Palau",
        "aliases": ["PLW", "Palau", "Republic of Palau"],
        "sovereign": None,
    },
    "PNG": {
        "name": "Papua New Guinea",
        "aliases": ["PNG", "Papua New Guinea", "Independent State of Papua New Guinea"],
        "sovereign": None,
    },
    "POL": {
        "name": "Poland",
        "aliases": ["POL", "Poland", "Republic of Poland"],
        "sovereign": None,
    },
    "POR": {
        "name": "Portugal",
        "aliases": ["POR", "PRT", "Portugal", "Portuguese Republic"],
        "sovereign": None,
    },
    "PRK": {
        "name": "North Korea",
        "aliases": [
            "PRK",
            "North Korea",
            "Democratic People's Republic of Korea",
            "DPRK",
            "Korea DPR",
        ],
        "sovereign": None,
    },
    "PUR": {
        "name": "Puerto Rico",
        "aliases": ["PUR", "PRI", "Puerto Rico", "Commonwealth of Puerto Rico", "PR"],
        "sovereign": "USA",
    },
    "QAT": {
        "name": "Qatar",
        "aliases": ["QAT", "Qatar", "State of Qatar", "QA"],
        "sovereign": None,
    },
    "ROU": {
        "name": "Romania",
        "aliases": ["ROU", "Romania"],
        "sovereign": None,
    },
    "RSA": {
        "name": "South Africa",
        "aliases": ["RSA", "ZAF", "South Africa", "Republic of South Africa"],
        "sovereign": None,
    },
    "RUS": {
        "name": "Russia",
        "aliases": ["RUS", "Russia", "Russian Federation", "RU"],
        "sovereign": None,
    },
    "RWA": {
        "name": "Rwanda",
        "aliases": ["RWA", "Rwanda", "Republic of Rwanda", "RW"],
        "sovereign": None,
    },
    "SAM": {
        "name": "Samoa",
        "aliases": [
            "SAM",
            "WSM",
            "Samoa",
            "Independent State of Samoa",
            "State of Samoa",
        ],
        "sovereign": None,
    },
    "SEN": {
        "name": "Senegal",
        "aliases": ["SEN", "Senegal", "Republic of Senegal"],
        "sovereign": None,
    },
    "SEY": {
        "name": "Seychelles",
        "aliases": ["SEY", "SYC", "Seychelles", "Republic of Seychelles"],
        "sovereign": None,
    },
    "SGP": {
        "name": "Singapore",
        "aliases": ["SGP", "Singapore", "Republic of Singapore"],
        "sovereign": None,
    },
    "SKN": {
        "name": "St Kitts & Nevis",
        "aliases": [
            "SKN",
            "KNA",
            "St. Kitts & Nevis",
            "St. Kitts",
            "Federation of St. Christopher & Nevis",
            "KN",
            "Kitts & Nevis",
            "Kitts",
            "St. Nevis",
            "Nevis",
        ],
        "sovereign": None,
    },
    "SLE": {
        "name": "Sierra Leone",
        "aliases": ["SLE", "Sierra Leone", "Republic of Sierra Leone", "SL"],
        "sovereign": None,
    },
    "SLO": {
        "name": "Slovenia",
        "aliases": ["SLO", "SVN", "Slovenia", "Republic of Slovenia"],
        "sovereign": None,
    },
    "SMR": {
        "name": "San Marino",
        "aliases": [
            "SMR",
            "San Marino",
            "Most Serene Republic of San Marino",
            "SM",
            "Republic of San Marino",
        ],
        "sovereign": None,
    },
    "SOL": {
        "name": "Solomon Islands",
        "aliases": ["SOL", "SLB", "Solomon Islands"],
        "sovereign": None,
    },
    "SOM": {
        "name": "Somalia",
        "aliases": ["SOM", "Somalia", "Federal Republic of Somalia"],
        "sovereign": None,
    },
    "SRB": {
        "name": "Serbia",
        "aliases": ["SRB", "Serbia", "Republic of Serbia"],
        "sovereign": None,
    },
    "SRI": {
        "name": "Sri Lanka",
        "aliases": [
            "SRI",
            "LKA",
            "Sri Lanka",
            "Democratic Socialist Republic of Sri Lanka",
        ],
        "sovereign": None,
    },
    "SSD": {
        "name": "South Sudan",
        "aliases": ["SSD", "South Sudan", "Republic of South Sudan", "SS"],
        "sovereign": None,
    },
    "STP": {
        "name": "Sao Tome & Principe",
        "aliases": [
            "STP",
            "Sao Tome & Principe",
            "Democratic Republic of Sao Tome & Principe",
        ],
        "sovereign": None,
    },
    "SUD": {
        "name": "Sudan",
        "aliases": [
            "SUD",
            "SDN",
            "Sudan",
            "Republic of the Sudan",
            "Republic of Sudan",
        ],
        "sovereign": None,
    },
    "SUI": {
        "name": "Switzerland",
        "aliases": ["SUI", "CHE", "Switzerland", "Swiss Confederation"],
        "sovereign": None,
    },
    "SUR": {
        "name": "Suriname",
        "aliases": ["SUR", "Suriname", "Republic of Suriname"],
        "sovereign": None,
    },
    "SVK": {
        "name": "Slovakia",
        "aliases": ["SVK", "Slovakia", "Slovak Republic"],
        "sovereign": None,
    },
    "SWE": {
        "name": "Sweden",
        "aliases": ["SWE", "Sweden", "Kingdom of Sweden"],
        "sovereign": None,
    },
    "SWZ": {
        "name": "Eswatini",
        "aliases": ["SWZ", "Eswatini", "Kingdom of Eswatini", "SZ", "Swaziland"],
        "sovereign": None,
    },
    "SYR": {
        "name": "Syria",
        "aliases": ["SYR", "Syria", "Syrian Arab Republic"],
        "sovereign": None,
    },
    "TAH": {
        "name": "French Polynesia",
        "aliases": ["TAH", "PYF", "French Polynesia", "Tahiti", "Polynesia"],
        "sovereign": "FRA",
    },
    "TAN": {
        "name": "Tanzania",
        "aliases": [
            "TAN",
            "TZA",
            "Tanzania",
            "United Republic of Tanzania",
            "TZ",
            "Tanzania United Republic of",
        ],
        "sovereign": None,
    },
    "TCI": {
        "name": "Turks & Caicos Islands",
        "aliases": [
            "TCI",
            "TCA",
            "Turks & Caicos Islands",
            "Turks",
            "Caicos",
            "Turks & Caicos",
            "Caicos Islands",
            "Turks Islands",
        ],
        "sovereign": "GBR",
    },
    "TGA": {
        "name": "Tonga",
        "aliases": ["TGA", "TON", "Tonga", "Kingdom of Tonga"],
        "sovereign": None,
    },
    "THA": {
        "name": "Thailand",
        "aliases": ["THA", "Thailand", "Kingdom of Thailand", "TH", "Thai"],
        "sovereign": None,
    },
    "TJK": {
        "name": "Tajikistan",
        "aliases": ["TJK", "Tajikistan", "Republic of Tajikistan", "TJ"],
        "sovereign": None,
    },
    "TKM": {
        "name": "Turkmenistan",
        "aliases": ["TKM", "Turkmenistan"],
        "sovereign": None,
    },
    "TLS": {
        "name": "Timor-Leste",
        "aliases": [
            "TLS",
            "Timor-Leste",
            "Democratic Republic of Timor-Leste",
            "East Timor",
            "Timor",
            "Timor Leste",
        ],
        "sovereign": None,
    },
    "TOG": {
        "name": "Togo",
        "aliases": ["TOG", "TGO", "Togo", "Togolese Republic", "TG", "Togolese"],
        "sovereign": None,
    },
    "TPE": {
        "name": "Taiwan",
        "aliases": [
            "TPE",
            "TWN",
            "Taiwan",
            "Republic of China Taiwan",
            "TW",
            "Republic of China",
            "Chinese Taipei",
            "Taiwan China",
        ],
        "sovereign": None,
    },
    "TTO": {
        "name": "Trinidad & Tobago",
        "aliases": [
            "TTO",
            "Trinidad & Tobago",
            "Republic of Trinidad & Tobago",
            "TT",
            "Trinidad",
            "Tobago",
            "Trinidad Tobago",
        ],
        "sovereign": None,
    },
    "TUN": {
        "name": "Tunisia",
        "aliases": ["TUN", "Tunisia", "Tunisian Republic", "TN", "Republic of Tunisia"],
        "sovereign": None,
    },
    "TUR": {
        "name": "Turkey",
        "aliases": [
            "TUR",
            "Turkiye",
            "Republic of Turkiye",
            "TR",
            "Republic of Turkey",
            "Turkey",
        ],
        "sovereign": None,
    },
    "TUV": {
        "name": "Tuvalu",
        "aliases": ["TUV", "Tuvalu", "TV"],
        "sovereign": None,
    },
    "UAE": {
        "name": "United Arab Emirates",
        "aliases": [
            "UAE",
            "ARE",
            "United Arab Emirates",
            "AE",
            "Arab Emirates",
            "Emirates",
        ],
        "sovereign": None,
    },
    "UGA": {
        "name": "Uganda",
        "aliases": ["UGA", "Uganda", "Republic of Uganda", "UG"],
        "sovereign": None,
    },
    "UKR": {
        "name": "Ukraine",
        "aliases": ["UKR", "Ukraine"],
        "sovereign": None,
    },
    "URU": {
        "name": "Uruguay",
        "aliases": [
            "URU",
            "URY",
            "Uruguay",
            "Oriental Republic of Uruguay",
            "Republic of Uruguay",
        ],
        "sovereign": None,
    },
    "USA": {
        "name": "United States",
        "aliases": [
            "USA",
            "United States",
            "United States of America",
            "US",
            "America",
        ],
        "sovereign": None,
    },
    "UZB": {
        "name": "Uzbekistan",
        "aliases": ["UZB", "Uzbekistan", "Republic of Uzbekistan", "UZ"],
        "sovereign": None,
    },
    "VAN": {
        "name": "Vanuatu",
        "aliases": ["VAN", "VUT", "Vanuatu", "Republic of Vanuatu"],
        "sovereign": None,
    },
    "VEN": {
        "name": "Venezuela",
        "aliases": [
            "VEN",
            "Venezuela",
            "Bolivarian Republic of Venezuela",
            "Venezuela Bolivarian Republic of",
        ],
        "sovereign": None,
    },
    "VIE": {
        "name": "Vietnam",
        "aliases": [
            "VIE",
            "VNM",
            "Vietnam",
            "Socialist Republic of Vietnam",
            "Republic of Vietnam",
        ],
        "sovereign": None,
    },
    "VIN": {
        "name": "St Vincent & the Grenadines",
        "aliases": [
            "VIN",
            "VCT",
            "St. Vincent & the Grenadines",
            "St. Vincent",
            "The Grenadines",
        ],
        "sovereign": None,
    },
    "YEM": {
        "name": "Yemen",
        "aliases": ["YEM", "Yemen", "Republic of Yemen", "YE", "Yemeni Republic"],
        "sovereign": None,
    },
    "ZAM": {
        "name": "Zambia",
        "aliases": ["ZAM", "ZMB", "Zambia", "Republic of Zambia"],
        "sovereign": None,
    },
    "ZIM": {
        "name": "Zimbabwe",
        "aliases": ["ZIM", "ZWE", "Zimbabwe", "Republic of Zimbabwe"],
        "sovereign": None,
    },
}


# ============================================================================
# DERIVED VALUE SETS
# ============================================================================

VALID_COUNTRY_CODES = frozenset(COUNTRIES.keys())
